[app]
url = "127.0.0.1"
port = "8000"

[dbDefault]
dbHost = "localhost"           #数据库连接地址
dbName = "mytest"              #数据库名称
dbUser = "root"                #数据库用户名
dbPasswd = "root"              #数据库密码
dbPort = "3306"                #数据库端口号
dbOpenconns_max = 2000           #最大连接数
dbIdleconns_max = 10            #最大空闲连接
dbType = "mysql"               #数据库类型